### PR TITLE
Sha1 function bug

### PR DESCRIPTION
**Pull request by ThierryO**
See #23 
The idea is that `sha1.function(x) == sha1.function(x, environment = TRUE)` and `sha1.function(x) != sha1.function(x, environment = FALSE)`

### CODE REVIEW

**Comment by ThierryO** [comment]
I've noticed some bugs. Please wait for some extra commits before merging this. I've forgot to forward the `...` in some of the functions.

**Comment by ThierryO** [comment]
I think I've solved the problem. I'll be doing some more tests after the weekend. Maybe we should bump the version number because some the hashed of some functions changed.

**Comment by eddelbuettel** [comment]
Well the next release will get a new minor number anyway.  And the changes affect only some of the sha1 functions, correct?

**Comment by ThierryO** [comment]
The sha1 changes for following cases:

- complex, Date or array classes
- lists or dataframes containing complex, Date or array classes

I'll add an entry to the ChangeLog

**Comment by eddelbuettel** [comment]
@ThierryO Should I wrap up a new release based on this?  Or wait til something else bubbles up? Are you otherwise ok with the code as in master here?

**Comment by ThierryO** [comment]
I've been using the new version for several days now. So far I've found no bugs or unexpected behaviour. You can wrap a new release.

**Comment by eddelbuettel** [comment]
Will do -- thanks for all your work on this sha1 improvement, and all the earlier work!

**Comment by eddelbuettel** [comment]
Grr, that's what I get for not using a matrix of R releases at the Travis check -- R-devel fails.  It reports something different:

```r
 ERROR
Running the tests in ‘tests/sha1Test.R’ failed.
Last 13 lines of output:
  > stopifnot(
  +     grepl("sha1\\(\\) has not method for the 'A', 'B' class", error.message)
  + )
  > 
  > stopifnot(sha1(formals(lm)) == "b8c1359ca3f9e16d64d3c67e50611ca724e4b27d")
  > stopifnot(sha1(formals(cov2cor)) == "9cd0f7430f50c301cf1b84cf3ee10b334d023809")
  > 
  > 
  > stopifnot(sha1(sum) == "098c0ebd5df77c19684f3f8c9aefc3ca810a159b")
  > stopifnot(sha1(sum) == sha1(sum, environment = TRUE))
  > stopifnot(sha1(sum) != sha1(sum, environment = FALSE))
  > 
  > stopifnot(sha1(glm) == "37d3e95bb1da86f0d1316acf655d12bb50288a20")
  Error: sha1(glm) == "37d3e95bb1da86f0d1316acf655d12bb50288a20" is not TRUE
  Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
   ‘sha1.Rmd’ using ‘UTF-8’ ... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 1 ERROR
See
  ‘/home/edd/git/digest.Rcheck/00check.log’
for details.

edd@max:~/git$ 
```

Maybe they changed `glm()` signatures?  Shall we skip the test?  Branch the test based on R version?

**Comment by ThierryO** [comment]
A better solution would be to write a custom function and calculate its hash. I used `glm()` because the `formals()` had a object of the `call` class. I'll see what I can do.

**Comment by ThierryO** [comment]
I hope that #56 solves the problem.

**Comment by eddelbuettel** [comment]
Sure does. Thanks!

**Pull request merged**
