### PR TITLE
Missing include for uint32_t

### PR DESCRIPTION
**Pull request by MichaelChirico**
Same provenance as https://github.com/RcppCore/Rcpp/pull/1272.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Same rules.  ChangeLog makes it happen more easily.   :grinning:

**Comment by MichaelChirico** [comment]
Sorry, you're too quick 🔫 🤠 🔫 

I'm editing in the web (the `Edit` button, not web VScode) where going one file at a time is slightly easier.

**Comment by eddelbuettel** [comment]
Yes I did that once or twice too and actually had trouble editing a second or third file in the same auto-fork it creates.  Standard fork is just so much easier and better and (ahem) allows you to run tests locally like any responsible committer would :heart_eyes:

**Comment by MichaelChirico** [comment]
Yes, I switch to VScode-on-web for multi-step changes... but running tests locally is easier said than done! Usually easier to let GH CI do the testing when there's compilation involved and I don't have my personal machine handy.

**Comment by eddelbuettel** [comment]
Now you have ChangeLog conflict to resolve, if you could.

**Comment by MichaelChirico** [comment]
I presume this sort of conflict is what Rcpp's .gitattributes is trying to avoid, is that right? I can add the same here if you'd like

https://github.com/RcppCore/Rcpp/blob/ba19cde26d9fbc490e0dcb9ff7b7d148488b2893/.gitattributes#L1

**Comment by MichaelChirico** [comment]
Style question, should there be two ChangeLog entries here, or one entry with two bullet points?

**Comment by eddelbuettel** [comment]
In this (very old) GNU Style I have only ever seen one 'date, author' entry which would then contain multiple bullet points.

You can group them and split them with an empty line between 'topics'.  There should be precedents in the same (20 year old !!) file.

**Comment by eddelbuettel** [comment]
Replaced by #196

**Pull request closed without merging**
