### PR TITLE
Add Loongarch info

### PR DESCRIPTION
**Pull request by fangyaling**
Add loongarch info

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Sure, can do -- can you remind me (for documentation purposes) which CPU types identify that way?

**Comment by fangyaling** [comment]
The LoongArch architecture (LoongArch) is an Instruction Set Architecture (ISA) that has Reduced Instruction Set Computer (RISC) style. And more infomation you can get from the link:https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html

**Comment by eddelbuettel** [comment]
Very good, thanks/. Almost too much detail.  

Could you maybe provide simpler information on
- what a common cpu name is
- who manufactures these 
- what brand names they may have
- what OS is typically running

to help me assess relevancy?

**Comment by eddelbuettel** [comment]
This helps somewhat:  https://en.wikipedia.org/wiki/Loongson

So is this a mostly / exclusively within-China Linux-style cpu?

**Comment by fangyaling** [comment]
Thanks for review. But now I will close this change for duplicate definition after checking the gcc define.

**Comment by eddelbuettel** [comment]
Oh, so the `gcc` define works for you?  Otherwise we can of course enable this.  I am just not that familiar with non-standard cpus (and for me that means non-Intel or AMD, I just don't keep track of the many ARM or MIPS variants ...).   

Let me know if this needs anything, if so we should support it.

**Comment by fangyaling** [comment]
OK. I got it.Thanks!

**Pull request closed without merging**
