### PR TITLE
Do not tests spookyhash test on big endian platforms

### PR DESCRIPTION
**Pull request by eddelbuettel**
@barracuda156 Can you take a look at this branch and check it on your platform?

### CODE REVIEW

**Comment by barracuda156** [comment]
@eddelbuettel Sure, will do today once back to the PowerMac.
Thanks for addressing this!

**Comment by barracuda156** [comment]
@eddelbuettel Building from e07137aa9de4296fa251f8d2fc20a40628527c49 commit, tests pass now, several examples fail:
```
--->  Testing R-digest
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-digest/R-digest/work/digest-e07137aa9de4296fa251f8d2fc20a40628527c49" && /opt/local/bin/R CMD check ./digest_0.6.35.3.tar.gz --no-manual --no-build-vignettes 
* using log directory ‘/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-digest/R-digest/work/digest-e07137aa9de4296fa251f8d2fc20a40628527c49/digest.Rcheck’
* using R version 4.4.1 (2024-06-14)
* using platform: powerpc-apple-darwin10.0.0d2 (32-bit)
* R was compiled by
    gcc-mp-13 (MacPorts gcc13 13.2.0_4+stdlib_flag) 13.2.0
    GNU Fortran (MacPorts gcc13 13.2.0_4+stdlib_flag) 13.2.0
* running under: OS X Snow Leopard 10.6
* using session charset: UTF-8
* using options ‘--no-manual --no-build-vignettes’
* checking for file ‘digest/DESCRIPTION’ ... OK
* this is package ‘digest’ version ‘0.6.35.3’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘digest’ can be installed ... OK
* used C compiler: ‘gcc-mp-13 (MacPorts gcc13 13.2.0_4+stdlib_flag) 13.2.0’
* used C++ compiler: ‘g++-mp-13 (MacPorts gcc13 13.2.0_4+stdlib_flag) 13.2.0’
* used SDK: ‘NA’‘NA’‘NA’‘NA’‘NA’‘NA’
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking code files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking whether startup messages can be suppressed ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in shell scripts ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking compiled code ... OK
* checking files in ‘vignettes’ ... WARNING
Files in the 'vignettes' directory but no files in 'inst/doc':
  ‘sha1.md’ ‘water.css’
* checking examples ... ERROR
Running examples in ‘digest-Ex.R’ failed
The error most likely occurred in:

> ### Name: digest
> ### Title: Create hash function digests for arbitrary R objects or files
> ### Aliases: digest
> ### Keywords: misc
> 
> ### ** Examples
> 
> 
> ## Standard RFC 1321 test vectors
> md5Input <-
+   c("",
+     "a",
+     "abc",
+     "message digest",
+     "abcdefghijklmnopqrstuvwxyz",
+     "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",
+     paste("12345678901234567890123456789012345678901234567890123456789012",
+           "345678901234567890", sep=""))
> md5Output <-
+   c("d41d8cd98f00b204e9800998ecf8427e",
+     "0cc175b9c0f1b6a831c399e269772661",
+     "900150983cd24fb0d6963f7d28e17f72",
+     "f96b697d7cb7938d525a2f31aaf161d0",
+     "c3fcd3d76192e4007dfb496cca67e13b",
+     "d174ab98d277d9f5a5611c2c9f419d9f",
+     "57edf4a22be3c955ac49da2e2107b67a")
> 
> for (i in seq(along=md5Input)) {
+   md5 <- digest(md5Input[i], serialize=FALSE)
+   stopifnot(identical(md5, md5Output[i]))
+ }
> 
> sha1Input <-
+   c("abc", "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq")
> sha1Output <-
+   c("a9993e364706816aba3e25717850c26c9cd0d89d",
+     "84983e441c3bd26ebaae4aa1f95129e5e54670f1")
> 
> for (i in seq(along=sha1Input)) {
+   sha1 <- digest(sha1Input[i], algo="sha1", serialize=FALSE)
+   stopifnot(identical(sha1, sha1Output[i]))
+ }
> 
> crc32Input <-
+   c("abc",
+     "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq")
> crc32Output <-
+   c("352441c2",
+     "171a3f5f")
> 
> for (i in seq(along=crc32Input)) {
+   crc32 <- digest(crc32Input[i], algo="crc32", serialize=FALSE)
+   stopifnot(identical(crc32, crc32Output[i]))
+ }
> 
> 
> sha256Input <-
+   c("abc",
+     "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq")
> sha256Output <-
+   c("ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
+     "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1")
> 
> for (i in seq(along=sha256Input)) {
+   sha256 <- digest(sha256Input[i], algo="sha256", serialize=FALSE)
+   stopifnot(identical(sha256, sha256Output[i]))
+ }
> 
> # SHA 512 example
> sha512Input <-
+   c("abc",
+     "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq")
> sha512Output <-
+   c(paste("ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a",
+           "2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f",
+           sep=""),
+     paste("204a8fc6dda82f0a0ced7beb8e08a41657c16ef468b228a8279be331a703c335",
+           "96fd15c13b1b07f9aa1d3bea57789ca031ad85c7a71dd70354ec631238ca3445",
+           sep=""))
> 
> for (i in seq(along=sha512Input)) {
+   sha512 <- digest(sha512Input[i], algo="sha512", serialize=FALSE)
+   stopifnot(identical(sha512, sha512Output[i]))
+ }
> 
> ## xxhash32 example
> xxhash32Input <-
+     c("abc",
+       "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq",
+       "")
> xxhash32Output <-
+     c("32d153ff",
+       "89ea60c3",
+       "02cc5d05")
> 
> for (i in seq(along=xxhash32Input)) {
+     xxhash32 <- digest(xxhash32Input[i], algo="xxhash32", serialize=FALSE)
+     cat(xxhash32, "\n")
+     stopifnot(identical(xxhash32, xxhash32Output[i]))
+ }
32d153ff 
89ea60c3 
02cc5d05 
> 
> ## xxhash64 example
> xxhash64Input <-
+     c("abc",
+       "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq",
+       "")
> xxhash64Output <-
+     c("44bc2cf5ad770999",
+       "f06103773e8585df",
+       "ef46db3751d8e999")
> 
> for (i in seq(along=xxhash64Input)) {
+     xxhash64 <- digest(xxhash64Input[i], algo="xxhash64", serialize=FALSE)
+     cat(xxhash64, "\n")
+     stopifnot(identical(xxhash64, xxhash64Output[i]))
+ }
44bc2cf5ad770999 
f06103773e8585df 
ef46db3751d8e999 
> 
> ## these outputs were calculated using mmh3 python package
> murmur32Input <-
+     c("abc",
+       "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq",
+       "")
> murmur32Output <-
+     c("b3dd93fa",
+       "ee925b90",
+       "00000000")
> 
> for (i in seq(along=murmur32Input)) {
+     murmur32 <- digest(murmur32Input[i], algo="murmur32", serialize=FALSE)
+     cat(murmur32, "\n")
+     stopifnot(identical(murmur32, murmur32Output[i]))
+ }
b3dd93fa 
ee925b90 
00000000 
> 
> ## these outputs were calculated using spooky python package
> spookyInput <-
+     c("a",
+       "abc",
+       "message digest")
> spookyOutput <-
+     c("bdc9bba09181101a922a4161f0584275",
+       "67c93775f715ab8ab01178caf86713c6",
+       "9630c2a55c0987a0db44434f9d67a192")
> 
> for (i in seq(along=spookyInput)) {
+     # skip = 30 skips the serialization header and just hashes the strings
+     spooky <- digest(spookyInput[i], algo="spookyhash", skip = 30)
+     cat(spooky, "\n")
+     stopifnot(identical(spooky, spookyOutput[i]))
+ }
1a108191a0bbc9bd754258f061412a92 
Error: identical(spooky, spookyOutput[i]) is not TRUE
Execution halted
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘tinytest.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes ... WARNING
Directory 'inst/doc' does not exist.
Package vignette without corresponding single PDF/HTML:
  ‘sha1.md’
* checking running R code from vignettes ...
  ‘sha1.md’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... SKIPPED
* DONE

Status: 1 ERROR, 2 WARNINGs
```

**Comment by barracuda156** [comment]
Tinytest output:
```

R version 4.4.1 (2024-06-14) -- "Race for Your Life"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: powerpc-apple-darwin10.0.0d2 (32-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> 
> if (requireNamespace("tinytest", quietly=TRUE)) {
+ 
+     ## Set a seed to make the test deterministic
+     set.seed(42)
+ 
+     ## there are several more granular ways to test files in a
+     ## tinytest directory, see its package vignette; tests can also
+     ## run once the package is installed using the same command
+ 
+     ## we need version 0.9.3 or later
+     if (packageVersion("tinytest") >= "0.9.3") {
+         ## expect_length is in tinytest 1.4.1
+         if (!"expect_length" %in% getNamespaceExports("tinytest")) {
+             expect_length <- function(x, n) tinytest::expect_equal(length(x), n)
+         }
+         tinytest::test_package("digest")
+     }
+ }

test_aes.R....................    0 tests    
test_aes.R....................    0 tests    
test_aes.R....................    0 tests    
test_aes.R....................    0 tests    
test_aes.R....................    0 tests    
test_aes.R....................    0 tests    
test_aes.R....................    0 tests    
test_aes.R....................    1 tests [0;32mOK[0m 
test_aes.R....................    2 tests [0;32mOK[0m 
test_aes.R....................    2 tests [0;32mOK[0m 
test_aes.R....................    2 tests [0;32mOK[0m 
test_aes.R....................    2 tests [0;32mOK[0m 
test_aes.R....................    2 tests [0;32mOK[0m 
test_aes.R....................    3 tests [0;32mOK[0m 
test_aes.R....................    4 tests [0;32mOK[0m 
test_aes.R....................    4 tests [0;32mOK[0m 
test_aes.R....................    4 tests [0;32mOK[0m 
test_aes.R....................    4 tests [0;32mOK[0m 
test_aes.R....................    4 tests [0;32mOK[0m 
test_aes.R....................    5 tests [0;32mOK[0m 
test_aes.R....................    6 tests [0;32mOK[0m 
test_aes.R....................    6 tests [0;32mOK[0m 
test_aes.R....................    6 tests [0;32mOK[0m 
test_aes.R....................    6 tests [0;32mOK[0m 
test_aes.R....................    6 tests [0;32mOK[0m 
test_aes.R....................    6 tests [0;32mOK[0m 
test_aes.R....................    7 tests [0;32mOK[0m 
test_aes.R....................    8 tests [0;32mOK[0m 
test_aes.R....................    8 tests [0;32mOK[0m 
test_aes.R....................    8 tests [0;32mOK[0m 
test_aes.R....................    8 tests [0;32mOK[0m 
test_aes.R....................    8 tests [0;32mOK[0m 
test_aes.R....................    9 tests [0;32mOK[0m 
test_aes.R....................    9 tests [0;32mOK[0m 
test_aes.R....................   10 tests [0;32mOK[0m 
test_aes.R....................   10 tests [0;32mOK[0m 
test_aes.R....................   10 tests [0;32mOK[0m 
test_aes.R....................   10 tests [0;32mOK[0m 
test_aes.R....................   10 tests [0;32mOK[0m 
test_aes.R....................   11 tests [0;32mOK[0m 
test_aes.R....................   11 tests [0;32mOK[0m 
test_aes.R....................   12 tests [0;32mOK[0m 
test_aes.R....................   12 tests [0;32mOK[0m 
test_aes.R....................   12 tests [0;32mOK[0m 
test_aes.R....................   12 tests [0;32mOK[0m 
test_aes.R....................   12 tests [0;32mOK[0m 
test_aes.R....................   12 tests [0;32mOK[0m 
test_aes.R....................   12 tests [0;32mOK[0m 
test_aes.R....................   12 tests [0;32mOK[0m 
test_aes.R....................   12 tests [0;32mOK[0m 
test_aes.R....................   13 tests [0;32mOK[0m 
test_aes.R....................   13 tests [0;32mOK[0m 
test_aes.R....................   14 tests [0;32mOK[0m 
test_aes.R....................   14 tests [0;32mOK[0m 
test_aes.R....................   14 tests [0;32mOK[0m 
test_aes.R....................   14 tests [0;32mOK[0m 
test_aes.R....................   15 tests [0;32mOK[0m 
test_aes.R....................   15 tests [0;32mOK[0m 
test_aes.R....................   16 tests [0;32mOK[0m 
test_aes.R....................   16 tests [0;32mOK[0m 
test_aes.R....................   17 tests [0;32mOK[0m 
test_aes.R....................   18 tests [0;32mOK[0m 
test_aes.R....................   18 tests [0;32mOK[0m 
test_aes.R....................   19 tests [0;32mOK[0m 
test_aes.R....................   20 tests [0;32mOK[0m 
test_aes.R....................   20 tests [0;32mOK[0m 
test_aes.R....................   20 tests [0;32mOK[0m 
test_aes.R....................   21 tests [0;32mOK[0m 
test_aes.R....................   22 tests [0;32mOK[0m 
test_aes.R....................   23 tests [0;32mOK[0m 
test_aes.R....................   24 tests [0;32mOK[0m 
test_aes.R....................   25 tests [0;32mOK[0m 
test_aes.R....................   25 tests [0;32mOK[0m 
test_aes.R....................   26 tests [0;32mOK[0m 
test_aes.R....................   26 tests [0;32mOK[0m 
test_aes.R....................   27 tests [0;32mOK[0m 
test_aes.R....................   28 tests [0;32mOK[0m 
test_aes.R....................   29 tests [0;32mOK[0m 
test_aes.R....................   30 tests [0;32mOK[0m 
test_aes.R....................   31 tests [0;32mOK[0m 
test_aes.R....................   32 tests [0;32mOK[0m 
test_aes.R....................   33 tests [0;32mOK[0m [0;34m0.2s[0m

test_blake3.R.................    0 tests    
test_blake3.R.................    0 tests    
test_blake3.R.................    0 tests    
test_blake3.R.................    0 tests    
test_blake3.R.................    1 tests [0;32mOK[0m 
test_blake3.R.................    1 tests [0;32mOK[0m 
test_blake3.R.................    2 tests [0;32mOK[0m 
test_blake3.R.................    2 tests [0;32mOK[0m 
test_blake3.R.................    2 tests [0;32mOK[0m 
test_blake3.R.................    5 tests [0;32mOK[0m 
test_blake3.R.................    5 tests [0;32mOK[0m 
test_blake3.R.................    5 tests [0;32mOK[0m 
test_blake3.R.................    5 tests [0;32mOK[0m 
test_blake3.R.................    5 tests [0;32mOK[0m 
test_blake3.R.................    5 tests [0;32mOK[0m 
test_blake3.R.................    6 tests [0;32mOK[0m 
test_blake3.R.................    6 tests [0;32mOK[0m 
test_blake3.R.................    6 tests [0;32mOK[0m 
test_blake3.R.................    6 tests [0;32mOK[0m 
test_blake3.R.................    6 tests [0;32mOK[0m 
test_blake3.R.................    6 tests [0;32mOK[0m 
test_blake3.R.................    7 tests [0;32mOK[0m [0;36m49ms[0m

test_crc32.R..................    0 tests    
test_crc32.R..................    0 tests    
test_crc32.R..................    0 tests    
test_crc32.R..................    0 tests    
test_crc32.R..................    0 tests    
test_crc32.R..................    1 tests [0;32mOK[0m 
test_crc32.R..................    1 tests [0;32mOK[0m 
test_crc32.R..................    2 tests [0;32mOK[0m [0;36m9ms[0m

test_digest.R.................    0 tests    
test_digest.R.................    0 tests    
test_digest.R.................    0 tests    
test_digest.R.................    7 tests [0;32mOK[0m 
test_digest.R.................    7 tests [0;32mOK[0m 
test_digest.R.................    8 tests [0;32mOK[0m 
test_digest.R.................    9 tests [0;32mOK[0m 
test_digest.R.................   10 tests [0;32mOK[0m 
test_digest.R.................   11 tests [0;32mOK[0m 
test_digest.R.................   12 tests [0;32mOK[0m 
test_digest.R.................   13 tests [0;32mOK[0m 
test_digest.R.................   20 tests [0;32mOK[0m 
test_digest.R.................   20 tests [0;32mOK[0m 
test_digest.R.................   20 tests [0;32mOK[0m 
test_digest.R.................   22 tests [0;32mOK[0m 
test_digest.R.................   22 tests [0;32mOK[0m 
test_digest.R.................   23 tests [0;32mOK[0m 
test_digest.R.................   25 tests [0;32mOK[0m 
test_digest.R.................   25 tests [0;32mOK[0m 
test_digest.R.................   25 tests [0;32mOK[0m 
test_digest.R.................   27 tests [0;32mOK[0m 
test_digest.R.................   27 tests [0;32mOK[0m 
test_digest.R.................   28 tests [0;32mOK[0m 
test_digest.R.................   30 tests [0;32mOK[0m 
test_digest.R.................   30 tests [0;32mOK[0m 
test_digest.R.................   30 tests [0;32mOK[0m 
test_digest.R.................   32 tests [0;32mOK[0m 
test_digest.R.................   32 tests [0;32mOK[0m 
test_digest.R.................   33 tests [0;32mOK[0m 
test_digest.R.................   33 tests [0;32mOK[0m 
test_digest.R.................   34 tests [0;32mOK[0m 
test_digest.R.................   34 tests [0;32mOK[0m 
test_digest.R.................   34 tests [0;32mOK[0m 
test_digest.R.................   37 tests [0;32mOK[0m 
test_digest.R.................   37 tests [0;32mOK[0m 
test_digest.R.................   38 tests [0;32mOK[0m 
test_digest.R.................   38 tests [0;32mOK[0m 
test_digest.R.................   38 tests [0;32mOK[0m 
test_digest.R.................   41 tests [0;32mOK[0m 
test_digest.R.................   41 tests [0;32mOK[0m 
test_digest.R.................   42 tests [0;32mOK[0m 
test_digest.R.................   42 tests [0;32mOK[0m 
test_digest.R.................   42 tests [0;32mOK[0m 
test_digest.R.................   45 tests [0;32mOK[0m 
test_digest.R.................   45 tests [0;32mOK[0m 
test_digest.R.................   46 tests [0;32mOK[0m 
test_digest.R.................   46 tests [0;32mOK[0m 
test_digest.R.................   46 tests [0;32mOK[0m 
test_digest.R.................   46 tests [0;32mOK[0m 
test_digest.R.................   46 tests [0;32mOK[0m 
test_digest.R.................   46 tests [0;32mOK[0m 
test_digest.R.................   46 tests [0;32mOK[0m 
test_digest.R.................   46 tests [0;32mOK[0m 
test_digest.R.................   49 tests [0;32mOK[0m 
test_digest.R.................   49 tests [0;32mOK[0m 
test_digest.R.................   50 tests [0;32mOK[0m 
test_digest.R.................   50 tests [0;32mOK[0m 
test_digest.R.................   50 tests [0;32mOK[0m 
test_digest.R.................   53 tests [0;32mOK[0m 
test_digest.R.................   53 tests [0;32mOK[0m 
test_digest.R.................   54 tests [0;32mOK[0m [0;36m53ms[0m

test_digest2int.R.............    0 tests    
test_digest2int.R.............    0 tests    
test_digest2int.R.............    0 tests    
test_digest2int.R.............    1 tests [0;32mOK[0m 
test_digest2int.R.............    1 tests [0;32mOK[0m 
test_digest2int.R.............    2 tests [0;32mOK[0m 
test_digest2int.R.............    3 tests [0;32mOK[0m 
test_digest2int.R.............    4 tests [0;32mOK[0m [0;36m8ms[0m

test_encoding.R...............    0 tests    
test_encoding.R...............    0 tests    [0;36m5ms[0m [Exited at #5: Skipping test on non-Windows platform]

test_hmac.R...................    0 tests    
test_hmac.R...................    0 tests    
test_hmac.R...................    0 tests    
test_hmac.R...................    1 tests [0;32mOK[0m 
test_hmac.R...................    1 tests [0;32mOK[0m 
test_hmac.R...................    1 tests [0;32mOK[0m 
test_hmac.R...................    2 tests [0;32mOK[0m 
test_hmac.R...................    2 tests [0;32mOK[0m 
test_hmac.R...................    2 tests [0;32mOK[0m 
test_hmac.R...................    3 tests [0;32mOK[0m 
test_hmac.R...................    3 tests [0;32mOK[0m 
test_hmac.R...................    3 tests [0;32mOK[0m 
test_hmac.R...................    4 tests [0;32mOK[0m 
test_hmac.R...................    4 tests [0;32mOK[0m 
test_hmac.R...................    4 tests [0;32mOK[0m 
test_hmac.R...................    5 tests [0;32mOK[0m 
test_hmac.R...................    5 tests [0;32mOK[0m 
test_hmac.R...................    5 tests [0;32mOK[0m 
test_hmac.R...................    6 tests [0;32mOK[0m 
test_hmac.R...................    6 tests [0;32mOK[0m 
test_hmac.R...................    6 tests [0;32mOK[0m 
test_hmac.R...................    7 tests [0;32mOK[0m 
test_hmac.R...................    7 tests [0;32mOK[0m 
test_hmac.R...................    7 tests [0;32mOK[0m 
test_hmac.R...................    8 tests [0;32mOK[0m 
test_hmac.R...................    8 tests [0;32mOK[0m 
test_hmac.R...................    8 tests [0;32mOK[0m 
test_hmac.R...................    9 tests [0;32mOK[0m 
test_hmac.R...................    9 tests [0;32mOK[0m 
test_hmac.R...................    9 tests [0;32mOK[0m 
test_hmac.R...................   10 tests [0;32mOK[0m 
test_hmac.R...................   10 tests [0;32mOK[0m 
test_hmac.R...................   10 tests [0;32mOK[0m 
test_hmac.R...................   11 tests [0;32mOK[0m 
test_hmac.R...................   11 tests [0;32mOK[0m 
test_hmac.R...................   11 tests [0;32mOK[0m 
test_hmac.R...................   12 tests [0;32mOK[0m 
test_hmac.R...................   12 tests [0;32mOK[0m 
test_hmac.R...................   13 tests [0;32mOK[0m 
test_hmac.R...................   13 tests [0;32mOK[0m 
test_hmac.R...................   13 tests [0;32mOK[0m 
test_hmac.R...................   14 tests [0;32mOK[0m [0;36m31ms[0m

test_misc.R...................    0 tests    
test_misc.R...................    0 tests    
test_misc.R...................    0 tests    
test_misc.R...................    0 tests    
test_misc.R...................   56 tests [0;32mOK[0m 
test_misc.R...................   56 tests [0;32mOK[0m 
test_misc.R...................   56 tests [0;32mOK[0m 
test_misc.R...................   56 tests [0;32mOK[0m 
test_misc.R...................   56 tests [0;32mOK[0m 
test_misc.R...................   57 tests [0;32mOK[0m 
test_misc.R...................   57 tests [0;32mOK[0m 
test_misc.R...................   57 tests [0;32mOK[0m 
test_misc.R...................   57 tests [0;32mOK[0m 
test_misc.R...................   57 tests [0;32mOK[0m [0;34m0.1s[0m

test_new_matrix_behaviour.R...    0 tests    [0;36m6ms[0m [Exited at #4: Skip tests for R 4.0.0 or later]

test_num2hex.R................    0 tests    
test_num2hex.R................    0 tests    
test_num2hex.R................    0 tests    
test_num2hex.R................    1 tests [0;32mOK[0m 
test_num2hex.R................    2 tests [0;32mOK[0m 
test_num2hex.R................    2 tests [0;32mOK[0m 
test_num2hex.R................    2 tests [0;32mOK[0m 
test_num2hex.R................    2 tests [0;32mOK[0m 
test_num2hex.R................    2 tests [0;32mOK[0m 
test_num2hex.R................    3 tests [0;32mOK[0m 
test_num2hex.R................    3 tests [0;32mOK[0m 
test_num2hex.R................    3 tests [0;32mOK[0m 
test_num2hex.R................    3 tests [0;32mOK[0m 
test_num2hex.R................    4 tests [0;32mOK[0m 
test_num2hex.R................    4 tests [0;32mOK[0m 
test_num2hex.R................    5 tests [0;32mOK[0m 
test_num2hex.R................    5 tests [0;32mOK[0m 
test_num2hex.R................    6 tests [0;32mOK[0m 
test_num2hex.R................    7 tests [0;32mOK[0m 
test_num2hex.R................    8 tests [0;32mOK[0m 
test_num2hex.R................    9 tests [0;32mOK[0m [0;36m31ms[0m

test_raw.R....................    0 tests    
test_raw.R....................    0 tests    
test_raw.R....................    0 tests    
test_raw.R....................    1 tests [0;32mOK[0m 
test_raw.R....................    1 tests [0;32mOK[0m 
test_raw.R....................    1 tests [0;32mOK[0m 
test_raw.R....................    2 tests [0;32mOK[0m 
test_raw.R....................    3 tests [0;32mOK[0m [0;36m8ms[0m

test_sha1.R...................    0 tests    
test_sha1.R...................    0 tests    
test_sha1.R...................    0 tests    
test_sha1.R...................    0 tests    
test_sha1.R...................    0 tests    
test_sha1.R...................    0 tests    
test_sha1.R...................    0 tests    
test_sha1.R...................    0 tests    
test_sha1.R...................    0 tests    
test_sha1.R...................    0 tests    
test_sha1.R...................    0 tests    
test_sha1.R...................    0 tests    
test_sha1.R...................    0 tests    
test_sha1.R...................    1 tests [0;32mOK[0m 
test_sha1.R...................    2 tests [0;32mOK[0m 
test_sha1.R...................    3 tests [0;32mOK[0m 
test_sha1.R...................    4 tests [0;32mOK[0m 
test_sha1.R...................    5 tests [0;32mOK[0m 
test_sha1.R...................    6 tests [0;32mOK[0m 
test_sha1.R...................    6 tests [0;32mOK[0m 
test_sha1.R...................    7 tests [0;32mOK[0m 
test_sha1.R...................    7 tests [0;32mOK[0m 
test_sha1.R...................    8 tests [0;32mOK[0m 
test_sha1.R...................    9 tests [0;32mOK[0m 
test_sha1.R...................   10 tests [0;32mOK[0m 
test_sha1.R...................   11 tests [0;32mOK[0m 
test_sha1.R...................   12 tests [0;32mOK[0m 
test_sha1.R...................   12 tests [0;32mOK[0m 
test_sha1.R...................   13 tests [0;32mOK[0m 
test_sha1.R...................   13 tests [0;32mOK[0m 
test_sha1.R...................   13 tests [0;32mOK[0m 
test_sha1.R...................   13 tests [0;32mOK[0m 
test_sha1.R...................   13 tests [0;32mOK[0m 
test_sha1.R...................   13 tests [0;32mOK[0m 
test_sha1.R...................   14 tests [0;32mOK[0m 
test_sha1.R...................   15 tests [0;32mOK[0m 
test_sha1.R...................   16 tests [0;32mOK[0m 
test_sha1.R...................   17 tests [0;32mOK[0m 
test_sha1.R...................   18 tests [0;32mOK[0m 
test_sha1.R...................   19 tests [0;32mOK[0m 
test_sha1.R...................   19 tests [0;32mOK[0m 
test_sha1.R...................   19 tests [0;32mOK[0m 
test_sha1.R...................   19 tests [0;32mOK[0m 
test_sha1.R...................   20 tests [0;32mOK[0m 
test_sha1.R...................   21 tests [0;32mOK[0m 
test_sha1.R...................   67 tests [0;32mOK[0m 
test_sha1.R...................   67 tests [0;32mOK[0m 
test_sha1.R...................   67 tests [0;32mOK[0m 
test_sha1.R...................   68 tests [0;32mOK[0m 
test_sha1.R...................   69 tests [0;32mOK[0m 
test_sha1.R...................   70 tests [0;32mOK[0m 
test_sha1.R...................   71 tests [0;32mOK[0m 
test_sha1.R...................   72 tests [0;32mOK[0m 
test_sha1.R...................   73 tests [0;32mOK[0m 
test_sha1.R...................   74 tests [0;32mOK[0m 
test_sha1.R...................   75 tests [0;32mOK[0m 
test_sha1.R...................   76 tests [0;32mOK[0m 
test_sha1.R...................   76 tests [0;32mOK[0m 
test_sha1.R...................   76 tests [0;32mOK[0m 
test_sha1.R...................   76 tests [0;32mOK[0m 
test_sha1.R...................   77 tests [0;32mOK[0m 
test_sha1.R...................   77 tests [0;32mOK[0m 
test_sha1.R...................   77 tests [0;32mOK[0m 
test_sha1.R...................   77 tests [0;32mOK[0m 
test_sha1.R...................   78 tests [0;32mOK[0m 
test_sha1.R...................   79 tests [0;32mOK[0m 
test_sha1.R...................   80 tests [0;32mOK[0m 
test_sha1.R...................   81 tests [0;32mOK[0m 
test_sha1.R...................   81 tests [0;32mOK[0m 
test_sha1.R...................   89 tests [0;32mOK[0m 
test_sha1.R...................   90 tests [0;32mOK[0m 
test_sha1.R...................   90 tests [0;32mOK[0m 
test_sha1.R...................   90 tests [0;32mOK[0m 
test_sha1.R...................   90 tests [0;32mOK[0m 
test_sha1.R...................   90 tests [0;32mOK[0m 
test_sha1.R...................  100 tests [0;32mOK[0m 
test_sha1.R...................  100 tests [0;32mOK[0m 
test_sha1.R...................  100 tests [0;32mOK[0m 
test_sha1.R...................  100 tests [0;32mOK[0m 
test_sha1.R...................  100 tests [0;32mOK[0m 
test_sha1.R...................  101 tests [0;32mOK[0m 
test_sha1.R...................  102 tests [0;32mOK[0m [0;34m1.2s[0m
All ok, 285 results (1.7s)
> 
> proc.time()
   user  system elapsed 
  2.097   0.408   2.502 
```

**Comment by eddelbuettel** [comment]
@barracuda156 Thanks.  Please try again with the updated branch. The example code will no longer compare to reference spookyhash values unless it runs on little endian

**Comment by barracuda156** [comment]
@eddelbuettel That worked, from 1dd9509fbb15f5e4ba4423b68fcf3903350be06c everything passes cleanly.

**Comment by eddelbuettel** [comment]
Sweet.  Thanks for checking.  I think I just roll this up as a release as it is a net improvement.

Thanks again for digging that blake3 patch for bigendian out.

**Comment by eddelbuettel** [comment]
I needed one more micro-iteration with CRAN (as my r-devel did not flag something their end did) but it is now 'on its way to CRAN'.

**Comment by barracuda156** [comment]
@eddelbuettel Awesome, thank you!

**Pull request merged**
