### PR TITLE
Fix sha1(Inf)

### LINKED ISSUE #120: sha1() fails on Inf
When running `sha1()` on `Inf`, an error occurs.

``` r
library(digest)
sha1(Inf)
#> Warning in num2hex(x, digits = digits, zapsmall = zapsmall): NAs introduced
#> by coercion to integer range
#> Error in if (any(zero)) {: missing value where TRUE/FALSE needed
```

<sup>Created on 2019-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by billdenney**
Fix #120 

`num2hex(Inf)` now returns `"Inf"`.

### CODE REVIEW

**Comment by billdenney** [comment]
@ThierryO, can you please review, too?

**Comment by billdenney** [comment]
I found an issue that `-Inf` was considered the same as `Inf`.  It is now fixed.

**Comment by eddelbuettel** [comment]
Good catch, and smart of me to be out and about at the Chicago Marathon all day.

Guess I'll merge shortly.

**Comment by billdenney** [comment]
That Chicago Marathon day was some of the best defensive programming that I've seen!  :)

**Comment by eddelbuettel** [comment]
Master plan didn't work all that well -- but I just hand-edited this directly in the other branch.  

Can you take a peek there to double-check?

**Pull request merged**
