### PR TITLE
Vignette on sha1()

### PR DESCRIPTION
**Pull request by ThierryO**
As requested by issue #22

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Can you try adding 

```
install:
  - ./travis-tool.sh install_aptget r-cran-knitr r-cran-rmarkdown
```

to the `.travis.yml` ?

**Comment by eddelbuettel** [comment]
Well done!  I just made one somewhat small set of changes in 49ed9da7fa9dd29d04b210e5842556c90a639fa2

I think this is ready.  So as discussed, shall I wrap it up for CRAN?  Shall we ship the vignette(-in-progress) as is, or exclude it?   I'd say might as well...

**Comment by ThierryO** [comment]
Let's go and move it to CRAN. I'd include the current vignette.

**Comment by eddelbuettel** [comment]
Yep, did that last eve -- it is now on CRAN as 0.6.9.  

I'll try to get a quick blog post out this evening.  This release was 'all you' -- big thanks.  We can now extend the vignette as time permits.

**Pull request merged**
