### PR TITLE
fix skipping bug for streaming_algos

### PR DESCRIPTION
**Pull request by kendonB**
Tests pass. 4x "OK" reports from rhub.

### CODE REVIEW

**Comment by kendonB** [comment]
The change makes sure the `skip` parameter gets set in `digest.R`

**Comment by eddelbuettel** [comment]
Will need one small update for the `digestTest.Rout.save` file; I'll deal with that later.

Thanks again for your persistence.  Really nice work.

**Comment by eddelbuettel** [comment]
Hi @kendonB as you may have seen we're on CRAN now, and gave you a big shout out of thank you (for which I couldn't CC on twitter as you seem twitter-less, and/or my search-fu is weak).

Looks like we are having bad luck with one platform: fedora-clang.  See https://cloud.r-project.org/web/checks/check_results_digest.html  We can probably get to it via rhub.

**Comment by kendonB** [comment]
Thanks to you as well! I am @kmb56 on twitter

**Comment by eddelbuettel** [comment]
And for what it is worth via `rhub::check(".", platform="fedora-clang-devel")` I _cannot_ replicate the failure.

**Pull request merged**
