### PR TITLE
Add blake3

### PR DESCRIPTION
**Pull request by dirkschumacher**
This is a first version of a possible blake3 integration as discussed in #60. It uses the portable [C imlementation](https://github.com/BLAKE3-team/BLAKE3/tree/master/c) of blake3 with special instructions deactivated.

Some remarks:
* This uses the portable version of blake3 without SIMD instructions and some commented code that is thus not needed. I guess adding that requires careful testing on all supported platforms and some `Makevars/configure` tweaks I assume. 
* I have just tested it on a Mac
* I included all required C files and added the public domain/apache2 license as a text file in `inst`. Not sure if that is the best way to do it.
* Tested it against the [rust implementation of mine](https://github.com/dirkschumacher/blake3). Might be worthwhile to double check with another package. Can do that before merging.
* The implementation in `digest.c` is a mix of the other algorithm calls and the readme example of blake3.
* ~~Haven't yet tested the file hashing api of `digest` with `blake3`~~

Happy to have your input. I am not C expert, but I am happy to learn :)

### CODE REVIEW

**Comment by dirkschumacher** [comment]
``` r
library(digest)
library(blake3) # remotes::install_github("dirkschumacher/blake3")
set.seed(42)
input <- charToRaw(paste0(sample(LETTERS, 1e6, replace = TRUE), collapse = ""))
microbenchmark::microbenchmark(
    md5 = digest(input, "md5", serialize = FALSE),
    sha1 = digest(input, "sha1", serialize = FALSE),
    sha2 = digest(input, "sha2", serialize = FALSE),
    blake3_digest = digest(input, "blake3", serialize = FALSE),
    blake3 = blake3_hash_raw(input),
    times = 1000
)
#> Unit: microseconds
#>           expr      min        lq     mean   median        uq       max neval
#>            md5 2894.653 2936.8285 3124.564 2977.124 3126.2540 16219.968  1000
#>           sha1 2951.886 2997.6510 3298.632 3049.490 3298.6150  6644.868  1000
#>           sha2 7379.573 7486.5440 8219.246 7665.810 8287.8310 24921.347  1000
#>  blake3_digest 1775.063 1818.1920 2061.605 1856.357 2041.7235  8725.557  1000
#>         blake3  354.202  381.1435  470.887  402.021  445.8255  3887.294  1000
```

<sup>Created on 2020-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by eddelbuettel** [comment]
Will take a look.  

As for tests, maybe take a look at the top of `inst/tinytest/test_digest.c` to see how we tested a few algos against known reference values.  Are there any such test vectors for blake3?

**Comment by eddelbuettel** [comment]
One more question:  any insight in timings?  How does this implementation (with all the history from digest etc) compare to your rust-based one?  How does either do relative to standard hashes?

**Comment by eddelbuettel** [comment]
Nice work!  I think it's ready to merge.

**Comment by eddelbuettel** [comment]
And just for closure I misread the failed Travis run just after the merge -- as I had done some work very recently on the [r-travis](http://eddelbuettel.github.io/r-travis/) script it uses I was overly paranoid I broke something.  Which I didn't -- the change was explicitly made to leave the old behavior in place.  It was a simple network issue which happens once very hundred or so runs.

But in any event the new PR #154 updates to bionic and R 4.0.0 which is good thing in and by itself.

**Comment by dirkschumacher** [comment]
Great! Happy to contribute to a package I personally use quite often. Just ran a benchmark with all available algorithms. Maybe I can get the SIMD stuff to work.

``` r
library(digest)
library(blake3) # remotes::install_github("dirkschumacher/blake3")
set.seed(42)
input <- charToRaw(paste0(sample(LETTERS, 1e6, replace = TRUE), collapse = ""))
microbenchmark::microbenchmark(
    md5 = digest(input, "md5", serialize = FALSE),
    sha1 = digest(input, "sha1", serialize = FALSE),
    crc32 = digest(input, "crc32", serialize = FALSE),
    sha256 = digest(input, "sha256", serialize = FALSE),
    sha512 = digest(input, "sha512", serialize = FALSE),
    xxhash32 = digest(input, "xxhash32", serialize = FALSE),
    xxhash64 = digest(input, "xxhash64", serialize = FALSE),
    murmur32 = digest(input, "murmur32", serialize = FALSE),
    blake3_digest = digest(input, "blake3", serialize = FALSE),
    blake3 = blake3_hash_raw(input),
    times = 1000
)
#> Unit: microseconds
#>           expr      min        lq       mean    median        uq       max
#>            md5 2895.168 3017.2160  3283.9535 3155.6535  3396.177  7267.650
#>           sha1 2951.735 3194.2915  4105.0421 3674.8815  4918.336 10917.943
#>          crc32  919.196  979.9085  1106.5130 1032.9240  1101.189  5328.990
#>         sha256 7380.138 8075.5820 10136.9435 9726.3065 11795.339 18750.473
#>         sha512 4106.084 4473.6725  5770.0278 5214.5135  6835.569 21211.104
#>       xxhash32  314.742  349.7840   446.3117  389.1700   437.366  3372.523
#>       xxhash64  109.276  146.1865   253.6527  194.3015   262.507  4477.475
#>       murmur32  431.516  472.2755   579.9507  514.8095   567.935  3208.060
#>  blake3_digest 1776.799 1913.2175  2434.1202 2157.9070  2844.448  7316.269
#>         blake3  355.031  399.8150   551.6886  449.7295   635.695  3705.388
#>  neval
#>   1000
#>   1000
#>   1000
#>   1000
#>   1000
#>   1000
#>   1000
#>   1000
#>   1000
#>   1000
```

<sup>Created on 2020-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by eddelbuettel** [comment]
I glanced at the files.  What would it take uncomment the portions in `blake_dispatch.c`? Did you try? Did you get errors?  Can we use `autoconf` to determine 'common' platforms and use those?

**Comment by eddelbuettel** [comment]
@dirkschumacher Any idea would it would take to make `blast3` fast?  Can we enable the optimizations currently commented out?

**Comment by dirkschumacher** [comment]
I think trying the non-portable, architecture specific code will probably help. 

The commented part was mainly to prevent a warning of an unused variable
https://github.com/eddelbuettel/digest/blob/master/src/blake3_dispatch.c#L149

Can try to look into it but not sure if I find the time this week.

**Comment by eddelbuettel** [comment]
Is there / was there some detection code?  Because the unconditional lines

```c
#define BLAKE3_NO_AVX512
#define BLAKE3_NO_SSE41
#define BLAKE3_NO_AVX2
```

do of course turn everything off.

**Comment by dirkschumacher** [comment]
I disabled that because I got compilation errors on my machine and I thought it would be better to start with robust portable version and investigate how to turn these instructions on afterwards.

**Comment by eddelbuettel** [comment]
I can probably help condition that via `configure` if we need to, or make it opt-in, or ...

But turning it off unconditionally seems to ... take a lot of shine off blake3.

**Comment by dirkschumacher** [comment]
I'll see what I can do and prepare a PR

**Comment by dirkschumacher** [comment]
So we could try the assembly version first, but this requires detection of the platform at compile time:
https://github.com/BLAKE3-team/BLAKE3/tree/master/c#x86

Currently we do essentially this (from the docs), which would be the fallback
```
gcc -shared -O3 -o libblake3.so -DBLAKE3_NO_SSE41 -DBLAKE3_NO_AVX2 -DBLAKE3_NO_AVX512 \
    blake3.c blake3_dispatch.c blake3_portable.c
```

In order to use the assembly version we need build it like this:
```
gcc -shared -O3 -o libblake3.so blake3.c blake3_dispatch.c blake3_portable.c \
    blake3_sse41_x86-64_unix.S blake3_avx2_x86-64_unix.S blake3_avx512_x86-64_unix.S
```
Where the `.S` files are available for `unix`, `windows_gnu` and `windows_msvc`.

Would we put the `.S` files in the `src/inst` folder and then control compilation in `Makevars`/`configure`?

If you can give me some hints, I can try to set it up.

**Comment by eddelbuettel** [comment]
Thanks for the docs pointer. That's a little head-scratcher:

```
gcc -c -fPIC -O3 -msse4.1 blake3_sse41.c -o blake3_sse41.o
gcc -c -fPIC -O3 -mavx2 blake3_avx2.c -o blake3_avx2.o
gcc -c -fPIC -O3 -mavx512f -mavx512vl blake3_avx512.c -o blake3_avx512.o
gcc -shared -O3 -o libblake3.so blake3.c blake3_dispatch.c blake3_portable.c \
    blake3_avx2.o blake3_avx512.o blake3_sse41.o
```

because I do know if CRAN allows this as 'portable'.  We could start by experimenting and add it in the Makefile (with the idea of hiding it behind a 'have to optin' env var).

**Comment by eddelbuettel** [comment]
We are still in limbo here in the sense that we have `blake3` but in a suboptimal build :-/

**Comment by eddelbuettel** [comment]
Would you be offended it I took blake3 out?  

In a sense we really need to add gazillions of new digesters as we have quite a few.  This one was _a priori_ of interest as it could have pushed the performance boundary but if we leave it a lame duck build not much.  Thoughts?

**Comment by dirkschumacher** [comment]
No, I can understand that. Although blake3 also has some nice security properties compared to other hash functions.

> Secure, unlike MD5 and SHA-1. And secure against length extension, unlike SHA-2.

**Comment by eddelbuettel** [comment]
Who could we "rope in" to help us?  I won;t have time to drive this anytime soon...

**Comment by dirkschumacher** [comment]
I might have some time in the coming 2 weeks, but of course can't promise anything :)

**Comment by dirkschumacher** [comment]
We could also do the development in a different branch so that it does not block other developments

**Comment by eddelbuettel** [comment]
Sure, it is not blocking anything though.  It is just not using blake3 to its speed potential.  But as you say there are other aspects.  So on balance it can stay.  

Would be nice to also have it fast though...

**Comment by eddelbuettel** [comment]
Meh. More blake3 trouble  -- at RHub's windows machine:

```
digest 0.6.25.3: ERROR

Build ID:   digest_0.6.25.3.tar.gz-e693f04864cf438fa537015ed12f117c
Platform:   Windows Server 2008 R2 SP1, R-devel, 32/64 bit
Submitted:  2 minutes 41.3 seconds ago
Build time: 2 minutes 17.2 seconds

ERRORS:
-------
* checking tests ...
** running tests for arch 'i386' ...
  Running 'tinytest.R'
 ERROR
Running the tests in 'tests/tinytest.R' failed.
Last 13 lines of output:
  Running test_sha1.R...................   90 tests OK
  Running test_sha1.R...................  100 tests OK
  Running test_sha1.R...................  100 tests OK
  Running test_sha1.R...................  100 tests OK
  Running test_sha1.R...................  100 tests OK
  Running test_sha1.R...................  100 tests OK
  Running test_sha1.R...................  102 tests OK
   call| expect_equal(current = res, target = "dea2b412aa90f1b43a06ca5e8b8feafec45ae1357971322749480f4e1572eaa2")
   diff| Expected 'dea2b412aa90f1b43a06ca5e8b8feafec45ae1357971322749480f4e1572eaa2', got 'c0058b2f040246a1cb3b274204f179562db2fbe0bb97fececbe95839e3acc7e7'
  ----- FAILED[data]: test_blake3.R<56--59>
   call| expect_equal(current = res, target = "a84aef38d9a7ad55fa458d9d1857eb895832e358385e8b6466c6af54ea46eeaa")
   diff| Expected 'a84aef38d9a7ad55fa458d9d1857eb895832e358385e8b6466c6af54ea46eeaa', got 'f55a1b2fc242ce4b4c20ecd0b84a8549aaafbe18ea51ffbb9e13d1719801f0c5'
  Error: ----- FAILED[data]: test_blake3.R<45--48>
  Running test_sha1.R...................  101 tests OK
  Execution halted
** running tests for arch 'x64' ...
 ERROR
Running the tests in 'tests/tinytest.R' failed.
Last 13 lines of output:
  Running test_sha1.R...................   90 tests OK
  Running test_sha1.R...................  100 tests OK
  Running test_sha1.R...................  100 tests OK
  Running test_sha1.R...................  100 tests OK
  Running test_sha1.R...................  100 tests OK
  Running test_sha1.R...................  101 tests OK
  Running test_sha1.R...................  102 tests OK
  Running test_sha1.R...................  100 tests OK
  Error: ----- FAILED[data]: test_blake3.R<45--48>
   call| expect_equal(current = res, target = "dea2b412aa90f1b43a06ca5e8b8feafec45ae1357971322749480f4e1572eaa2")
   diff| Expected 'dea2b412aa90f1b43a06ca5e8b8feafec45ae1357971322749480f4e1572eaa2', got 'c0058b2f040246a1cb3b274204f179562db2fbe0bb97fececbe95839e3acc7e7'
  ----- FAILED[data]: test_blake3.R<56--59>
   call| expect_equal(current = res, target = "a84aef38d9a7ad55fa458d9d1857eb895832e358385e8b6466c6af54ea46eeaa")
  Execution halted
   diff| Expected 'a84aef38d9a7ad55fa458d9d1857eb895832e358385e8b6466c6af54ea46eeaa', got 'f55a1b2fc242ce4b4c20ecd0b84a8549aaafbe18ea51ffbb9e13d1719801f0c5'



See the full build log:
HTML: https://builder.r-hub.io/status/digest_0.6.25.3.tar.gz-e693f04864cf438fa537015ed12f117c
Text: https://builder.r-hub.io/status/original/digest_0.6.25.3.tar.gz-e693f04864cf438fa537015ed12f117c
Artifacts: https://artifacts.r-hub.io/digest_0.6.25.3.tar.gz-e693f04864cf438fa537015ed12f117c

Have questions, suggestions or want to report a bug?
Please file an issue ticket at GitHub at
https://github.com/r-hub/rhub/issues

Thank You for using the R-hub builder.
 
(c) 2016 The R Consortium
```

Any ideas why @dirkschumacher ?

**Comment by eddelbuettel** [comment]
Maybe. Apparently it is only the final test that blows up, not the preceding one.

**Comment by dirkschumacher** [comment]
I can contribute a fix.

**Comment by eddelbuettel** [comment]
If you can look into I would appreciate it.  I am currently testing `if windows exit_file(...)` to avoid the issue.

**Comment by eddelbuettel** [comment]
It _probably_ only needs binary mode in the file write.

**Comment by eddelbuettel** [comment]
This now makes the package break Solaris as @johnmount just let me know. See https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/digest-00install.html for

```
* installing to library ‘/home/ripley/R/Lib32’
* installing *source* package ‘digest’ ...
** package ‘digest’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
/home/ripley/developerstudio12.6/bin/CC -std=c++11 -library=stdcpp,CrunG3 -I"/home/ripley/R/cc/include" -DNDEBUG   -I/usr/local/include  -KPIC  -O -xlibmil -xtarget=native -xcache=generic -nofstore  -c SpookyV2.cpp -o SpookyV2.o
/home/ripley/developerstudio12.6/bin/cc -xc99 -I"/home/ripley/R/cc/include" -DNDEBUG   -I/usr/local/include  -KPIC  -O -xlibmieee -xlibmil -xtarget=native -xcache=generic -nofstore  -c aes.c -o aes.o
/home/ripley/developerstudio12.6/bin/cc -xc99 -I"/home/ripley/R/cc/include" -DNDEBUG   -I/usr/local/include  -KPIC  -O -xlibmieee -xlibmil -xtarget=native -xcache=generic -nofstore  -c blake3.c -o blake3.o
/home/ripley/developerstudio12.6/bin/cc -xc99 -I"/home/ripley/R/cc/include" -DNDEBUG   -I/usr/local/include  -KPIC  -O -xlibmieee -xlibmil -xtarget=native -xcache=generic -nofstore  -c blake3_dispatch.c -o blake3_dispatch.o
"blake3_dispatch.c", line 21: #error: "Unimplemented!"
cc: acomp failed for blake3_dispatch.c
*** Error code 2
make: Fatal error: Command failed for target `blake3_dispatch.o'
Current working directory /tmp/Rtmp1YaaBE/R.INSTALL3cd812977d59/digest/src
ERROR: compilation failed for package ‘digest’
* removing ‘/home/ripley/R/Lib32/digest’

real        2.8
user        2.1
sys         0.6
```

Should we setup something that let's `blake3` compile but be 'empty' on these non-GNU platforms ?  This code is unlikely to make CRAN happy:

```
#if defined(IS_X86)
#if defined(_MSC_VER)
#include <intrin.h>
#elif defined(__GNUC__)
#include <immintrin.h>
#else
#error "Unimplemented!"
#endif
#endif
```

**Comment by eddelbuettel** [comment]
Turns out we can actually simply comment out that whole block because all the 'hairy' code needing intrinsics is ... already parked and inactive.  A quick and dirty version is this:

```diff
modified   src/blake3_dispatch.c
@@ -12,15 +12,15 @@
 
 #include "blake3_impl.h"
 
-#if defined(IS_X86)
-#if defined(_MSC_VER)
-#include <intrin.h>
-#elif defined(__GNUC__)
-#include <immintrin.h>
-#else
-#error "Unimplemented!"
-#endif
-#endif
+/* #if defined(IS_X86) */
+/* #if defined(_MSC_VER) */
+/* #include <intrin.h> */
+/* #elif defined(__GNUC__) */
+/* #include <immintrin.h> */
+/* #else */
+/* #error "Unimplemented!" */
+/* #endif */
+/* #endif */
 
 // This function is disabled in this R package for now
 // #if defined(IS_X86)
```

**Pull request merged**
