### PR TITLE
Add sha1.formula()

### LINKED ISSUE #122: Attempt at sha1.formula Method
I just tried to write an sha1.formula method (as mentioned in #23), but I couldn't get the test to work.  My attempts were:

Function:

```r
sha1.formula <- function(x, digits = 14L, zapsmall = 7L, ..., algo = "sha1"){
    dots <- list(...)
    if (is.null(dots$environment)) {
        dots$environment <- TRUE
    }
    if (isTRUE(dots$environment)) {
        y <- append(
            as.list(x),
            list(environment = digest(environment(x), algo = algo))
        )
    } else {
        y <- as.list(x)
    }
    y <- vapply(
        y,
        sha1,
        digits = digits,
        zapsmall = zapsmall,
        environment = dots$environment,
        ... = dots,
        algo = algo,
        FUN.VALUE = NA_character_
    )
    attr(y, "digest::sha1") <- attr_sha1(
        x = y, digits = digits, zapsmall = zapsmall, algo = algo, dots
    )
    digest(y, algo = algo)
}
```

Test:

```r
x.formula <- a~b+c|d
expect_true(
    identical(
        sha1(x.formula, environment=FALSE),
        {
            y <- sapply(
                X=as.list(x.formula),
                FUN=sha1
            )
            attr(y, "digest::sha1") <- list(
                digits=14L,
                zapsmall=7L,
                algo="sha1"
            )
            sha1(y)
        }
    )
)
```

Edited to add the formula being tested.

### PR DESCRIPTION
**Pull request by billdenney**
Fix #122 

I accidentally added this on top of #121, but since that was given a (near) green-light already, I didn't go to the hassle of rolling it back to master.  (With the subsequent advantage that if both are good, it simplifies the merge! :) )

### CODE REVIEW

**Comment by eddelbuettel** [comment]
I may just squash merge both then.  Ok with you?

**Comment by billdenney** [comment]
Works for me.

**Comment by eddelbuettel** [comment]
Looks like I messed this up.  Let me see if I can pull your branch here and clean up.

**Comment by ThierryO** [comment]
This is a nice addition. Thanks for the contribution @billdenney

**Pull request merged**
