### PR TITLE
use vapply instead of the error-prone sapply

### PR DESCRIPTION
**Pull request by mllg**
Fix for #27.

### CODE REVIEW

**Comment by mllg** [comment]
On a second thought, my commit is not very clever...
```r
all.equal(sha1(list()), sha1(character(0)))
```

**Comment by mllg** [comment]
The previous issue is fixed. However, I'm curious if this is supposed to happen:
```r
# TRUE on CRAN and patched
identical(sha1(list(a = 1)), sha1(data.frame(a = 1)))
```
Same issue for other R objects with attributes.

**Comment by ThierryO** [comment]
Thanks for the PR. I'll add some more stuff.

**Comment by ThierryO** [comment]
I've added my changes into a [PR at mllg:master](https://github.com/mllg/digest/pull/1).

Should `sha1()` take attributes of the original object into account? Now they are ignored except is the simple cases where `sha1()` is just a wrapper for `digest()`.

**Comment by eddelbuettel** [comment]
Thank you both!   I'll also add Michel to the Authors list.

(And I now see why people like 'squashed commits' on PR but I don't mind explicit ones.)

**Pull request merged**
